---

  - apt:
      name: rfkill
      state: present
    tags:
      - section3
      - section3.7

  - name: 3.7 Ensure wireless interfaces are disabled (Not Scored)
    when: lxd_container == False    
    command: rfkill block wifi
    tags:
      - section3
      - section3.7
